#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$OpenBSD: Makefile,v 1.1 2002/02/28 06:58:21 millert Exp $

PROG=	deroff

.include <bsd.prog.mk>

CFLAGS+=-Wno-strict-prototypes -Wno-unused-parameter 
CFLAGS+=-Wno-implicit-function-declaration -Wno-cast-qual
CFLAGS+=-Wno-missing-variable-declarations -Wno-sign-compare
